language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t darkoohrid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true darkoohrid/docker-react npm run test